"""hall_name_and_desc_limit

Revision ID: 02083d8604f2
Revises: fe119c44a736
Create Date: 2026-03-25 06:21:45.044352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02083d8604f2'
down_revision: Union[str, Sequence[str], None] = 'fe119c44a736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index('idx_room_search_vector', table_name='halls')
  op.drop_index('idx_room_name_trgm', table_name='halls')
  op.drop_column('halls', 'search_vector')
  
  op.alter_column('halls', 'name',
    existing_type=sa.VARCHAR(length=255),
    type_=sa.String(length=100),
    existing_nullable=False)
  op.alter_column('halls', 'description',
    existing_type=sa.TEXT(),
    type_=sa.String(length=1000),
    existing_nullable=False)
  
  op.add_column(
    'halls', 
    sa.Column(
      'search_vector', 
      postgresql.TSVECTOR(), 
      sa.Computed(
        "setweight(to_tsvector('english', name), 'A') || setweight(to_tsvector('english', description), 'B')", 
        persisted=True
      ), 
      nullable=False
    )
  )
  op.create_index('idx_room_search_vector', 'halls', ['search_vector'], unique=False, postgresql_using='gin')
  op.create_index('idx_room_name_trgm', 'halls', ['name'], unique=False, postgresql_using='gist', postgresql_ops={'name': 'gist_trgm_ops'})
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index('idx_room_search_vector', table_name='halls')
  op.drop_index('idx_room_name_trgm', table_name='halls')
  op.drop_column('halls', 'search_vector')
  
  op.alter_column('halls', 'description',
    existing_type=sa.String(length=1000),
    type_=sa.TEXT(),
    existing_nullable=False)
  op.alter_column('halls', 'name',
    existing_type=sa.String(length=100),
    type_=sa.VARCHAR(length=255),
    existing_nullable=False)
  
  op.add_column(
    'halls', 
    sa.Column(
      'search_vector', 
      postgresql.TSVECTOR(), 
      sa.Computed(
        "setweight(to_tsvector('english', name), 'A') || setweight(to_tsvector('english', description), 'B')", 
        persisted=True
      ), 
      nullable=False
    )
  )
  op.create_index('idx_room_search_vector', 'halls', ['search_vector'], unique=False, postgresql_using='gin')
  op.create_index('idx_room_name_trgm', 'halls', ['name'], unique=False, postgresql_using='gist', postgresql_ops={'name': 'gist_trgm_ops'})
  # ### end Alembic commands ###
