"""add_superadmin_role

Revision ID: 164b30aad75f
Revises: 69624269a60e
Create Date: 2026-02-24 15:13:59.861706

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '164b30aad75f'
down_revision: Union[str, Sequence[str], None] = '69624269a60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role ADD VALUE 'SUPERADMIN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
