"""fts_and_pg_trgm

Revision ID: 1cc5ca065aab
Revises: e52023eeecc2
Create Date: 2026-02-19 12:16:23.939404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cc5ca065aab'
down_revision: Union[str, Sequence[str], None] = 'e52023eeecc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.add_column('halls', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', name), 'A') || setweight(to_tsvector('english', description), 'B')", persisted=True), nullable=False))
    op.create_index('idx_room_name_trgm', 'halls', ['name'], unique=False, postgresql_using='gist', postgresql_ops={'name': 'gist_trgm_ops'})
    op.create_index('idx_room_search_vector', 'halls', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_room_search_vector', table_name='halls', postgresql_using='gin')
    op.drop_index('idx_room_name_trgm', table_name='halls', postgresql_using='gist', postgresql_ops={'name': 'gist_trgm_ops'})
    op.drop_column('halls', 'search_vector')
    # ### end Alembic commands ###
