"""add_is_deleted_User_column

Revision ID: 76653034288f
Revises: 1cc5ca065aab
Create Date: 2026-02-22 13:05:55.854895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76653034288f'
down_revision: Union[str, Sequence[str], None] = '1cc5ca065aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('halls', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=True,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'english\'::regconfig, (name)::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, description), \'B\'::"char"))', persisted=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.alter_column('halls', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=False,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'english\'::regconfig, (name)::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, description), \'B\'::"char"))', persisted=True))
    # ### end Alembic commands ###
