"""fix_reservation_constraint

Revision ID: ba8441224232
Revises: 4e93dfe40be1
Create Date: 2026-01-30 18:41:55.196369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8441224232'
down_revision: Union[str, Sequence[str], None] = '4e93dfe40be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_hall_date'), 'reservations', type_='unique')
    op.create_index('uq_hallid_resdate_active', 'reservations', ['hall_id', 'reservation_date'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_hallid_resdate_active', table_name='reservations', postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"))
    op.create_unique_constraint(op.f('uq_hall_date'), 'reservations', ['hall_id', 'reservation_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
