"""add_timestamp_columns_and_indexes

Revision ID: fe119c44a736
Revises: 164b30aad75f
Create Date: 2026-02-28 11:57:55.291110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe119c44a736'
down_revision: Union[str, Sequence[str], None] = '164b30aad75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
      'reservations',
      sa.Column('created_at',
      sa.DateTime(timezone=True),
      server_default=sa.func.now(),
      nullable=False)
    )
    
    op.add_column(
      'reservations',
      sa.Column('updated_at',
      sa.DateTime(timezone=True),
      server_default=sa.func.now(),
      nullable=False)
    )
    
    op.create_index('idx_reservation_date', 'reservations', ['reservation_date'], unique=False)
    op.create_index('idx_reservation_status', 'reservations', ['status'], unique=False)
    op.create_index('idx_reservation_user_id', 'reservations', ['user_id'], unique=False)
    op.create_index('idx_reservation_user_status', 'reservations', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reservation_user_status', table_name='reservations')
    op.drop_index('idx_reservation_user_id', table_name='reservations')
    op.drop_index('idx_reservation_status', table_name='reservations')
    op.drop_index('idx_reservation_date', table_name='reservations')
    op.drop_column('reservations', 'updated_at')
    op.drop_column('reservations', 'created_at')
    # ### end Alembic commands ###
